name: Autoformat files

on:
  pull_request:
    paths:
      - "**.php"
      - "**.blade.php"

jobs:
  autoformat:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Nix
        uses: cachix/install-nix-action@v25

      - name: Run PHP-CS-Fixer
        run: |
          nix run nixpkgs#php84Packages.php-cs-fixer -- fix .

      - name: Run Blade Formatter
        run: |
          nix run nixpkgs#blade-formatter -- --write .

      - name: Push Back Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "format: format files"
          branch: ${{ github.head_ref }}
